### ISSUE TITLE
Spamming message of namespace missing

### ISSUE THREAD

**Issue by equidevium** [cs-util-com/cscore#89]
I keep getting a missing namespace even though my code is not missing. 

The message is also sent for CsCore assembly as well which makes it even more confusing. 

![image](https://user-images.githubusercontent.com/11783663/217218270-da7f056c-12fd-4e06-b344-c5256733bd99.png)

**Comment by cs-util** [comment]
Thanks for reporting, I did some improvements to the warnings logging now so that it does not spam anymore. They will be included in the next release.

And also see https://github.com/cs-util-com/cscore/commit/1d99d7292067ecc506f1c9a50ef760138104ca46 how to add your own assembly or type blacklist entries, eg for plugins you dont have control over that you never want to show up as warnings
